name: phish_detective
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1
  sqflite: ^2.3.2
  path: ^1.8.3
  another_telephony: ^0.4.1
  # sms_advanced: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9 # Or latest version
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/logo.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
